BTAT-11493 Removing API version feature switch
hmrc/vat-subscription pull request #247
Opened 2023-04-26 11:00 UTC by paulfirmstone

# Pull Request Checklist
* [x] Branch is rebased with master
* [x] Added Unit Tests for changed functionality
* [x] Ran `sbt clean compile coverage test it:test coverageReport`, all tests pass and coverage meets minimum
* [ ] Checked libraries are up to date with `sbt validate`. (If applicable) library updates are done in a separate, single commit
* [x] Ran Acceptance tests as per the story. Query in group slack if unsure of test packs to run.
* [x] Ran Performance tests as per the story. Query in group slack if unsure of test packs to run.
* [ ] (If applicable) raised app-config-* PRs
* [ ] (If applicable) added Integration Test

2023-04-26 15:07 UTC, paulfirmstone commented
app config PRs:
https://github.com/hmrc/app-config-qa/pull/18369
https://github.com/hmrc/app-config-staging/pull/12697
https://github.com/hmrc/app-config-production/pull/18129

2023-05-02 09:29 UTC, lewishay requested changes

2023-05-02 09:29 UTC, lewishay commented on app/models/updateVatSubscription/request/RequestedChanges.scala
> +  val DESApi1365Writes: AppConfig => Writes[RequestedChanges] = _ => Writes { model =>
Underscoring the `AppConfig` param here means it's still there but just not being given a name. Looks like we have no need for `AppConfig` in this reads anymore so can we remove it instead? i.e. converting this function from:
`AppConfig => Writes[RequestedChanges] = _ => Writes`...
to
`Writes[RequestedChanges] = Writes`...

2023-05-02 09:29 UTC, lewishay commented on app/models/updateVatSubscription/request/UpdateVatSubscription.scala
> +  implicit val reads: AppConfig => Reads[ControlInformation] = _ => for {
Same comment here as with the `RequestedChanges` model

2023-05-02 11:15 UTC, merged